Further doc changes
jboss-fuse/application-templates pull request #143
Opened 2020-09-08 18:45 UTC by cunningt

- Moved dashboards to monitoring directory alongside prometheus instructions for openshift 4
- moved older prometheus documentation to openshift3
- updated README documentation

2020-09-08 19:14 UTC, oscerd approved these changes

2020-09-10 04:17 UTC, tadayosi commented on README.md
> +# Monitoring
It should be `##` instead of `#`.

2020-09-10 04:18 UTC, tadayosi commented on README.md
> -## Fuse Apicurito
Is it ok to remove the Apicurito section as well?  It doesn't seem to be related to monitoring.

2020-09-10 04:21 UTC, tadayosi commented on openshift3/prometheus-openshift3.md
> +## Fuse Apicurito
I'm not sure if Apicurito falls under the monitoring category. Isn't it rather a API designing tool?  Please correct me if I'm wrong.

2020-09-10 04:24 UTC, tadayosi commented on monitoring/prometheus.md
> +![Exchanges Total](https://github.com/jboss-fuse/application-templates/raw/master/monitoring/exchangestotal.png)
For the newly added png files, you can utilise the `img/` directory as well, so that the monitoring directory doesn't get cluttered :-)

2020-09-10 04:27 UTC, tadayosi requested changes
There are a few nitpicks. Please have a look at them.

2020-09-10 18:15 UTC, cunningt commented
Good points and incorporated the changes requested.

2020-09-10 18:15 UTC, merged